export const reviewData = [
  {
    id: 0,
    nickname: '작성자 1',
    likes: 24,
    title: '예산시장에 가보았다',
    descrpition: '[님아 그시장을 가오 158화]에서 소개된 충남 예산시장에 서 먹부림도 부리고왔습니다.',
    createdAt: '2022-02-04',
    score: 3,
  },
  {
    id: 1,
    nickname: '여행자 2',
    likes: 15,
    title: '서울 광장시장 탐방',
    descrpition: '광장시장 맛집을 찾아다녔습니다. 빈대떡이 정말 맛있었어요.',
    createdAt: '2023-03-15',
    score: 2,
  },
  {
    id: 2,
    nickname: '맛집헌터',
    likes: 42,
    title: '부산 자갈치 시장 후기',
    descrpition: '부산 자갈치 시장에서 신선한 해산물을 맛봤습니다.',
    createdAt: '2022-11-22',
    score: 1,
  },
  {
    id: 3,
    nickname: '여행객',
    likes: 30,
    title: '대구 서문시장 탐방기',
    descrpition: '대구 서문시장에서 다양한 먹거리를 즐겼습니다.',
    createdAt: '2023-01-10',
    score: 4,
  },
  {
    id: 4,
    nickname: '시장러버',
    likes: 27,
    title: '전주 남부시장 투어',
    descrpition: '전주 남부시장에서 한옥마을 방문 후 시장 구경했습니다.',
    createdAt: '2023-05-05',
    score: 5,
  },
  {
    id: 5,
    nickname: '푸드파이터',
    likes: 50,
    title: '인천 신포시장 먹방',
    descrpition: '신포시장에서 유명한 닭강정을 먹었습니다. 정말 최고였어요!',
    createdAt: '2022-07-20',
    score: 2,
  },
  {
    id: 6,
    nickname: '시장매니아',
    likes: 35,
    title: '수원 남문시장 체험기',
    descrpition: '수원 남문시장에서 다양한 전통 음식을 체험했습니다.',
    createdAt: '2023-04-25',
    score: 1,
  },
  {
    id: 7,
    nickname: '트래블러',
    likes: 29,
    title: '광주 송정시장 방문기',
    descrpition: '광주 송정시장에서 신선한 농산물과 음식을 즐겼습니다.',
    createdAt: '2022-10-14',
    score: 2,
  },
  {
    id: 8,
    nickname: '먹방여신',
    likes: 33,
    title: '대전 중앙시장 후기',
    descrpition: '대전 중앙시장에서 먹부림을 즐기고 왔습니다.',
    createdAt: '2022-12-30',
    score: 4,
  },
  {
    id: 9,
    nickname: '시장탐험가',
    likes: 41,
    title: '제주 동문시장 탐방',
    descrpition: '제주 동문시장에서 신선한 해산물과 과일을 맛봤습니다.',
    createdAt: '2023-02-18',
    score: 5,
  },
];
